// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// NSE_DeepState_TestHarness_generation.cpp and NSE_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double NSE(NumericVector yhat, NumericVector y);

TEST(ldsr_deepstate_test,NSE_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector yhat  = RcppDeepState_NumericVector();
  qs::c_qsave(yhat,"/home/akhila/fuzzer_packages/fuzzedpackages/ldsr/inst/testfiles/NSE/inputs/yhat.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "yhat values: "<< yhat << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/ldsr/inst/testfiles/NSE/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    NSE(yhat,y);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
