// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// TriangleTesselation__DeepState_TestHarness_generation.cpp and TriangleTesselation__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List TriangleTesselation_(NumericVector v0, NumericVector v1, NumericVector v2, NumericVector origin, int lineBreak);

TEST(icosa_deepstate_test,TriangleTesselation__test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector v0  = RcppDeepState_NumericVector();
  qs::c_qsave(v0,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/TriangleTesselation_/inputs/v0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "v0 values: "<< v0 << std::endl;
  NumericVector v1  = RcppDeepState_NumericVector();
  qs::c_qsave(v1,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/TriangleTesselation_/inputs/v1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "v1 values: "<< v1 << std::endl;
  NumericVector v2  = RcppDeepState_NumericVector();
  qs::c_qsave(v2,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/TriangleTesselation_/inputs/v2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "v2 values: "<< v2 << std::endl;
  NumericVector origin  = RcppDeepState_NumericVector();
  qs::c_qsave(origin,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/TriangleTesselation_/inputs/origin.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "origin values: "<< origin << std::endl;
  IntegerVector lineBreak(1);
  lineBreak[0]  = RcppDeepState_int();
  qs::c_qsave(lineBreak,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/TriangleTesselation_/inputs/lineBreak.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lineBreak values: "<< lineBreak << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    TriangleTesselation_(v0,v1,v2,origin,lineBreak[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
