// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// simData_rls_DeepState_TestHarness_generation.cpp and simData_rls_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::vec simData_rls(double mu, double sig, int n);

TEST(robustBLME_deepstate_test,simData_rls_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector mu(1);
  mu[0]  = RcppDeepState_double();
  qs::c_qsave(mu,"/home/akhila/fuzzer_packages/fuzzedpackages/robustBLME/inst/testfiles/simData_rls/inputs/mu.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericVector sig(1);
  sig[0]  = RcppDeepState_double();
  qs::c_qsave(sig,"/home/akhila/fuzzer_packages/fuzzedpackages/robustBLME/inst/testfiles/simData_rls/inputs/sig.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sig values: "<< sig << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  qs::c_qsave(n,"/home/akhila/fuzzer_packages/fuzzedpackages/robustBLME/inst/testfiles/simData_rls/inputs/n.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    simData_rls(mu[0],sig[0],n[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
