// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// get_ayanamsa_ex_ut_DeepState_TestHarness_generation.cpp and get_ayanamsa_ex_ut_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List get_ayanamsa_ex_ut(double jd_ut, int iflag);

TEST(swephR_deepstate_test,get_ayanamsa_ex_ut_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector jd_ut(1);
  jd_ut[0]  = RcppDeepState_double();
  qs::c_qsave(jd_ut,"/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/get_ayanamsa_ex_ut/inputs/jd_ut.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "jd_ut values: "<< jd_ut << std::endl;
  IntegerVector iflag(1);
  iflag[0]  = RcppDeepState_int();
  qs::c_qsave(iflag,"/home/akhila/fuzzer_packages/fuzzedpackages/swephR/inst/testfiles/get_ayanamsa_ex_ut/inputs/iflag.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "iflag values: "<< iflag << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    get_ayanamsa_ex_ut(jd_ut[0],iflag[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
