// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Sum_C_DeepState_TestHarness_generation.cpp and Sum_C_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double Sum_C(NumericVector AA);

TEST(CKLRT_deepstate_test,Sum_C_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector AA  = RcppDeepState_NumericVector();
  qs::c_qsave(AA,"/home/akhila/fuzzer_packages/fuzzedpackages/CKLRT/inst/testfiles/Sum_C/inputs/AA.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "AA values: "<< AA << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Sum_C(AA);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
