// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// HACWeightC_DeepState_TestHarness_generation.cpp and HACWeightC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::colvec HACWeightC(int iLag);

TEST(DriftBurstHypothesis_deepstate_test,HACWeightC_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector iLag(1);
  iLag[0]  = RcppDeepState_int();
  qs::c_qsave(iLag,"/home/akhila/fuzzer_packages/fuzzedpackages/DriftBurstHypothesis/inst/testfiles/HACWeightC/inputs/iLag.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "iLag values: "<< iLag << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    HACWeightC(iLag[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
