# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gcdist1 <- function(lon, lat, eps) {
    .Call(`_gear_gcdist1`, lon, lat, eps)
}

gcdist2 <- function(lon1, lat1, lon2, lat2, eps) {
    .Call(`_gear_gcdist2`, lon1, lat1, lon2, lat2, eps)
}

eucdist1 <- function(x, y, eps) {
    .Call(`_gear_eucdist1`, x, y, eps)
}

eucdist2 <- function(x1, y1, x2, y2, eps) {
    .Call(`_gear_eucdist2`, x1, y1, x2, y2, eps)
}

