// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// k_chol
NumericMatrix k_chol(NumericMatrix GlobalMat);
RcppExport SEXP _krige_k_chol(SEXP GlobalMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type GlobalMat(GlobalMatSEXP);
    rcpp_result_gen = Rcpp::wrap(k_chol(GlobalMat));
    return rcpp_result_gen;
END_RCPP
}
// k_chol2inv
NumericMatrix k_chol2inv(NumericMatrix GlobalMat);
RcppExport SEXP _krige_k_chol2inv(SEXP GlobalMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type GlobalMat(GlobalMatSEXP);
    rcpp_result_gen = Rcpp::wrap(k_chol2inv(GlobalMat));
    return rcpp_result_gen;
END_RCPP
}
// k_eigenvalue
NumericVector k_eigenvalue(NumericMatrix GlobalMat);
RcppExport SEXP _krige_k_eigenvalue(SEXP GlobalMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type GlobalMat(GlobalMatSEXP);
    rcpp_result_gen = Rcpp::wrap(k_eigenvalue(GlobalMat));
    return rcpp_result_gen;
END_RCPP
}
// k_inv
NumericMatrix k_inv(NumericMatrix GlobalMat);
RcppExport SEXP _krige_k_inv(SEXP GlobalMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type GlobalMat(GlobalMatSEXP);
    rcpp_result_gen = Rcpp::wrap(k_inv(GlobalMat));
    return rcpp_result_gen;
END_RCPP
}
// k_distmat
NumericMatrix k_distmat(NumericMatrix Mat);
RcppExport SEXP _krige_k_distmat(SEXP MatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Mat(MatSEXP);
    rcpp_result_gen = Rcpp::wrap(k_distmat(Mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_krige_k_chol", (DL_FUNC) &_krige_k_chol, 1},
    {"_krige_k_chol2inv", (DL_FUNC) &_krige_k_chol2inv, 1},
    {"_krige_k_eigenvalue", (DL_FUNC) &_krige_k_eigenvalue, 1},
    {"_krige_k_inv", (DL_FUNC) &_krige_k_inv, 1},
    {"_krige_k_distmat", (DL_FUNC) &_krige_k_distmat, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_krige(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
