// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ordersetdiff_DeepState_TestHarness_generation.cpp and ordersetdiff_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

std::vector<std::string> ordersetdiff(CharacterVector vector, CharacterVector remove);

TEST(bnclassify_deepstate_test,ordersetdiff_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  CharacterVector vector  = RcppDeepState_CharacterVector();
  qs::c_qsave(vector,"/home/akhila/fuzzer_packages/fuzzedpackages/bnclassify/inst/testfiles/ordersetdiff/inputs/vector.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vector values: "<< vector << std::endl;
  CharacterVector remove  = RcppDeepState_CharacterVector();
  qs::c_qsave(remove,"/home/akhila/fuzzer_packages/fuzzedpackages/bnclassify/inst/testfiles/ordersetdiff/inputs/remove.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "remove values: "<< remove << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ordersetdiff(vector,remove);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
