// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sim_ptr_DeepState_TestHarness_generation.cpp and sim_ptr_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

XPtr<sim> sim_ptr(string dict, string model, string idf, string stop, string user);

TEST(jiebaR_deepstate_test,sim_ptr_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  string dict  = RcppDeepState_string();
  qs::c_qsave(dict,"/home/akhila/fuzzer_packages/fuzzedpackages/jiebaR/inst/testfiles/sim_ptr/inputs/dict.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dict values: "<< dict << std::endl;
  string model  = RcppDeepState_string();
  qs::c_qsave(model,"/home/akhila/fuzzer_packages/fuzzedpackages/jiebaR/inst/testfiles/sim_ptr/inputs/model.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "model values: "<< model << std::endl;
  string idf  = RcppDeepState_string();
  qs::c_qsave(idf,"/home/akhila/fuzzer_packages/fuzzedpackages/jiebaR/inst/testfiles/sim_ptr/inputs/idf.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "idf values: "<< idf << std::endl;
  string stop  = RcppDeepState_string();
  qs::c_qsave(stop,"/home/akhila/fuzzer_packages/fuzzedpackages/jiebaR/inst/testfiles/sim_ptr/inputs/stop.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "stop values: "<< stop << std::endl;
  string user  = RcppDeepState_string();
  qs::c_qsave(user,"/home/akhila/fuzzer_packages/fuzzedpackages/jiebaR/inst/testfiles/sim_ptr/inputs/user.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "user values: "<< user << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sim_ptr(dict,model,idf,stop,user);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
