// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hazard_DeepState_TestHarness_generation.cpp and hazard_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List hazard(NumericVector y1, NumericVector y2, NumericVector lev, NumericVector wt);

TEST(DStree_deepstate_test,hazard_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector y1  = RcppDeepState_NumericVector();
  qs::c_qsave(y1,"/home/akhila/fuzzer_packages/fuzzedpackages/DStree/inst/testfiles/hazard/inputs/y1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y1 values: "<< y1 << std::endl;
  NumericVector y2  = RcppDeepState_NumericVector();
  qs::c_qsave(y2,"/home/akhila/fuzzer_packages/fuzzedpackages/DStree/inst/testfiles/hazard/inputs/y2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y2 values: "<< y2 << std::endl;
  NumericVector lev  = RcppDeepState_NumericVector();
  qs::c_qsave(lev,"/home/akhila/fuzzer_packages/fuzzedpackages/DStree/inst/testfiles/hazard/inputs/lev.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lev values: "<< lev << std::endl;
  NumericVector wt  = RcppDeepState_NumericVector();
  qs::c_qsave(wt,"/home/akhila/fuzzer_packages/fuzzedpackages/DStree/inst/testfiles/hazard/inputs/wt.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wt values: "<< wt << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hazard(y1,y2,lev,wt);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
