// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cdm_rcpp_generalized_distance_method_DeepState_TestHarness_generation.cpp and cdm_rcpp_generalized_distance_method_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List cdm_rcpp_generalized_distance_method(Rcpp::NumericMatrix data, Rcpp::NumericMatrix dataresp, Rcpp::NumericMatrix idealresp, Rcpp::NumericVector theta, Rcpp::NumericVector a, Rcpp::NumericVector b);

TEST(CDM_deepstate_test,cdm_rcpp_generalized_distance_method_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix data  = RcppDeepState_NumericMatrix();
  qs::c_qsave(data,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_generalized_distance_method/inputs/data.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "data values: "<< data << std::endl;
  NumericMatrix dataresp  = RcppDeepState_NumericMatrix();
  qs::c_qsave(dataresp,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_generalized_distance_method/inputs/dataresp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dataresp values: "<< dataresp << std::endl;
  NumericMatrix idealresp  = RcppDeepState_NumericMatrix();
  qs::c_qsave(idealresp,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_generalized_distance_method/inputs/idealresp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "idealresp values: "<< idealresp << std::endl;
  NumericVector theta  = RcppDeepState_NumericVector();
  qs::c_qsave(theta,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_generalized_distance_method/inputs/theta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta values: "<< theta << std::endl;
  NumericVector a  = RcppDeepState_NumericVector();
  qs::c_qsave(a,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_generalized_distance_method/inputs/a.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a values: "<< a << std::endl;
  NumericVector b  = RcppDeepState_NumericVector();
  qs::c_qsave(b,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_generalized_distance_method/inputs/b.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cdm_rcpp_generalized_distance_method(data,dataresp,idealresp,theta,a,b);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
