// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// IntegrMultiCpp
List IntegrMultiCpp(NumericMatrix alpha2, NumericVector linvec2, NumericMatrix Phibig2, NumericMatrix tUeach2, NumericMatrix Ueach2, NumericMatrix Tmat2, NumericMatrix Phidoublebig2, NumericMatrix Udoubleeach2, NumericMatrix XW2);
RcppExport SEXP _PenCoxFrail_IntegrMultiCpp(SEXP alpha2SEXP, SEXP linvec2SEXP, SEXP Phibig2SEXP, SEXP tUeach2SEXP, SEXP Ueach2SEXP, SEXP Tmat2SEXP, SEXP Phidoublebig2SEXP, SEXP Udoubleeach2SEXP, SEXP XW2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type alpha2(alpha2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type linvec2(linvec2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Phibig2(Phibig2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tUeach2(tUeach2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Ueach2(Ueach2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Tmat2(Tmat2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Phidoublebig2(Phidoublebig2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Udoubleeach2(Udoubleeach2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type XW2(XW2SEXP);
    rcpp_result_gen = Rcpp::wrap(IntegrMultiCpp(alpha2, linvec2, Phibig2, tUeach2, Ueach2, Tmat2, Phidoublebig2, Udoubleeach2, XW2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PenCoxFrail_IntegrMultiCpp", (DL_FUNC) &_PenCoxFrail_IntegrMultiCpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_PenCoxFrail(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
