// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mloglik1c
double mloglik1c(NumericVector jtms, double TT, Function nu, NumericVector gcoef, Function Inu);
RcppExport SEXP _IHSEP_mloglik1c(SEXP jtmsSEXP, SEXP TTSEXP, SEXP nuSEXP, SEXP gcoefSEXP, SEXP InuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type jtms(jtmsSEXP);
    Rcpp::traits::input_parameter< double >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< Function >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gcoef(gcoefSEXP);
    Rcpp::traits::input_parameter< Function >::type Inu(InuSEXP);
    rcpp_result_gen = Rcpp::wrap(mloglik1c(jtms, TT, nu, gcoef, Inu));
    return rcpp_result_gen;
END_RCPP
}
// mloglik1d
double mloglik1d(NumericVector jtms, double TT, Function nu, NumericVector gcoef, Function Inu);
RcppExport SEXP _IHSEP_mloglik1d(SEXP jtmsSEXP, SEXP TTSEXP, SEXP nuSEXP, SEXP gcoefSEXP, SEXP InuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type jtms(jtmsSEXP);
    Rcpp::traits::input_parameter< double >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< Function >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gcoef(gcoefSEXP);
    Rcpp::traits::input_parameter< Function >::type Inu(InuSEXP);
    rcpp_result_gen = Rcpp::wrap(mloglik1d(jtms, TT, nu, gcoef, Inu));
    return rcpp_result_gen;
END_RCPP
}
// mloglik1e
double mloglik1e(NumericVector jtms, double TT, NumericVector nuvs, NumericVector gcoef, double InuT);
RcppExport SEXP _IHSEP_mloglik1e(SEXP jtmsSEXP, SEXP TTSEXP, SEXP nuvsSEXP, SEXP gcoefSEXP, SEXP InuTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type jtms(jtmsSEXP);
    Rcpp::traits::input_parameter< double >::type TT(TTSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nuvs(nuvsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gcoef(gcoefSEXP);
    Rcpp::traits::input_parameter< double >::type InuT(InuTSEXP);
    rcpp_result_gen = Rcpp::wrap(mloglik1e(jtms, TT, nuvs, gcoef, InuT));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP mloglik1a(SEXP);
RcppExport SEXP mloglik1b(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_IHSEP_mloglik1c", (DL_FUNC) &_IHSEP_mloglik1c, 5},
    {"_IHSEP_mloglik1d", (DL_FUNC) &_IHSEP_mloglik1d, 5},
    {"_IHSEP_mloglik1e", (DL_FUNC) &_IHSEP_mloglik1e, 5},
    {"mloglik1a", (DL_FUNC) &mloglik1a, 10},
    {"mloglik1b", (DL_FUNC) &mloglik1b,  8},
    {NULL, NULL, 0}
};

RcppExport void R_init_IHSEP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
