// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calculate_resids_DeepState_TestHarness_generation.cpp and calculate_resids_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calculate_resids(NumericMatrix predictions, NumericVector response);

TEST(bartBMA_deepstate_test,calculate_resids_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix predictions  = RcppDeepState_NumericMatrix();
  qs::c_qsave(predictions,"/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/calculate_resids/inputs/predictions.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "predictions values: "<< predictions << std::endl;
  NumericVector response  = RcppDeepState_NumericVector();
  qs::c_qsave(response,"/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/calculate_resids/inputs/response.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "response values: "<< response << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calculate_resids(predictions,response);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
