# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

order_vector <- function(x, decreasing) {
    .Call(`_xyz_order_vector`, x, decreasing)
}

sort_using_order_numvec <- function(x, x_o) {
    invisible(.Call(`_xyz_sort_using_order_numvec`, x, x_o))
}

sort_using_order_intmat <- function(x, x_o) {
    invisible(.Call(`_xyz_sort_using_order_intmat`, x, x_o))
}

sample_uniform <- function(range, n) {
    .Call(`_xyz_sample_uniform`, range, n)
}

sample_int_replace <- function(probabilities, n) {
    .Call(`_xyz_sample_int_replace`, probabilities, n)
}

prod_matrix_vector <- function(X, r) {
    .Call(`_xyz_prod_matrix_vector`, X, r)
}

colsum_index <- function(X, indexes) {
    .Call(`_xyz_colsum_index`, X, indexes)
}

absolute_covariates <- function(X, Y) {
    .Call(`_xyz_absolute_covariates`, X, Y)
}

absolute_covariates_pairs <- function(pairs, X, Y) {
    .Call(`_xyz_absolute_covariates_pairs`, pairs, X, Y)
}

clean_pairs <- function(pairs) {
    .Call(`_xyz_clean_pairs`, pairs)
}

translate_to_binary <- function(X, max_number_of_iterations) {
    .Call(`_xyz_translate_to_binary`, X, max_number_of_iterations)
}

estimate_background_interaction_frequency <- function(X, Y, number_of_samples) {
    .Call(`_xyz_estimate_background_interaction_frequency`, X, Y, number_of_samples)
}

find_strongest_pairs <- function(pairs, X, Y, max_number_of_pairs) {
    .Call(`_xyz_find_strongest_pairs`, pairs, X, Y, max_number_of_pairs)
}

equalpairs <- function(u, v, ou, ov, max_number_of_pairs) {
    .Call(`_xyz_equalpairs`, u, v, ou, ov, max_number_of_pairs)
}

projected_equal_pairs <- function(X, Y, number_of_runs, max_number_of_collisions, negative) {
    .Call(`_xyz_projected_equal_pairs`, X, Y, number_of_runs, max_number_of_collisions, negative)
}

naive_interaction_search <- function(X, Y, max_number_of_pairs) {
    .Call(`_xyz_naive_interaction_search`, X, Y, max_number_of_pairs)
}

interaction_search <- function(X, Y, number_of_runs, max_number_of_pairs, negative, binary) {
    .Call(`_xyz_interaction_search`, X, Y, number_of_runs, max_number_of_pairs, negative, binary)
}

interaction_search_low_level <- function(X_binary, X, Y, number_of_runs, max_number_of_pairs) {
    .Call(`_xyz_interaction_search_low_level`, X_binary, X, Y, number_of_runs, max_number_of_pairs)
}

soft_threshold <- function(beta_tilde, normalization, lambda, alpha) {
    .Call(`_xyz_soft_threshold`, beta_tilde, normalization, lambda, alpha)
}

create_lambda_sequence <- function(lambda_max, n_lambda, factor_eps_inv) {
    .Call(`_xyz_create_lambda_sequence`, lambda_max, n_lambda, factor_eps_inv)
}

scan_main_effects <- function(X, Y, residuals, main_effects, beta_main, lambdas, alpha, r, add_max, strong) {
    .Call(`_xyz_scan_main_effects`, X, Y, residuals, main_effects, beta_main, lambdas, alpha, r, add_max, strong)
}

scale_intr <- function(X, pair_x, pair_y) {
    .Call(`_xyz_scale_intr`, X, pair_x, pair_y)
}

scan_intr_effects <- function(X, Y, X_bin, residuals, intr_effects, beta_intr, intr_vars, lambdas, alpha, r, projections, strong) {
    .Call(`_xyz_scan_intr_effects`, X, Y, X_bin, residuals, intr_effects, beta_intr, intr_vars, lambdas, alpha, r, projections, strong)
}

update_intr_final <- function(intr_effects, beta_intr) {
    invisible(.Call(`_xyz_update_intr_final`, intr_effects, beta_intr))
}

calculate_xbeta <- function(X, Y, intercept, main_effects, beta_main, intr_effects, beta_intr, intr_vars, r) {
    .Call(`_xyz_calculate_xbeta`, X, Y, intercept, main_effects, beta_main, intr_effects, beta_intr, intr_vars, r)
}

calculate_residuals <- function(X, Y, intercept, main_effects, beta_main, intr_effects, beta_intr, intr_vars, r) {
    .Call(`_xyz_calculate_residuals`, X, Y, intercept, main_effects, beta_main, intr_effects, beta_intr, intr_vars, r)
}

iterate <- function(X, Y, residuals, intercept, main_effects, beta_main, intr_effects, beta_intr, intr_vars, weights, lambdas, alpha, r, maxiter_inner) {
    .Call(`_xyz_iterate`, X, Y, residuals, intercept, main_effects, beta_main, intr_effects, beta_intr, intr_vars, weights, lambdas, alpha, r, maxiter_inner)
}

update_intr_vars <- function(X, intr_effects, standardize, r) {
    .Call(`_xyz_update_intr_vars`, X, intr_effects, standardize, r)
}

clean_all_effects <- function(main_effects, beta_main, intr_effects, beta_intr, r) {
    invisible(.Call(`_xyz_clean_all_effects`, main_effects, beta_main, intr_effects, beta_intr, r))
}

warm_start <- function(main_effects, beta_main, intr_effects, beta_intr, r) {
    invisible(.Call(`_xyz_warm_start`, main_effects, beta_main, intr_effects, beta_intr, r))
}

gaussiglmnet <- function(X, Y, lambdas, alpha, standardize, max_main_effects, max_interaction_effects, max_outer, number_of_nnis_runs) {
    .Call(`_xyz_gaussiglmnet`, X, Y, lambdas, alpha, standardize, max_main_effects, max_interaction_effects, max_outer, number_of_nnis_runs)
}

