// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CVfastCpp
double CVfastCpp(const arma::mat& x, const arma::mat& ky);
RcppExport SEXP _MAVE_CVfastCpp(SEXP xSEXP, SEXP kySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ky(kySEXP);
    rcpp_result_gen = Rcpp::wrap(CVfastCpp(x, ky));
    return rcpp_result_gen;
END_RCPP
}
// MAVEfastCpp
List MAVEfastCpp(NumericMatrix x, NumericMatrix y, CharacterVector method, double max_dim, double screen);
RcppExport SEXP _MAVE_MAVEfastCpp(SEXP xSEXP, SEXP ySEXP, SEXP methodSEXP, SEXP max_dimSEXP, SEXP screenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type max_dim(max_dimSEXP);
    Rcpp::traits::input_parameter< double >::type screen(screenSEXP);
    rcpp_result_gen = Rcpp::wrap(MAVEfastCpp(x, y, method, max_dim, screen));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MAVE_CVfastCpp", (DL_FUNC) &_MAVE_CVfastCpp, 2},
    {"_MAVE_MAVEfastCpp", (DL_FUNC) &_MAVE_MAVEfastCpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_MAVE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
