// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fun_subless_DeepState_TestHarness_generation.cpp and fun_subless_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

LogicalMatrix fun_subless(NumericVector u, NumericVector lessthan);

TEST(ALassoSurvIC_deepstate_test,fun_subless_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector u  = RcppDeepState_NumericVector();
  qs::c_qsave(u,"/home/akhila/fuzzer_packages/fuzzedpackages/ALassoSurvIC/inst/testfiles/fun_subless/inputs/u.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "u values: "<< u << std::endl;
  NumericVector lessthan  = RcppDeepState_NumericVector();
  qs::c_qsave(lessthan,"/home/akhila/fuzzer_packages/fuzzedpackages/ALassoSurvIC/inst/testfiles/fun_subless/inputs/lessthan.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lessthan values: "<< lessthan << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fun_subless(u,lessthan);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
