// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cdm_rcpp_din_deterministic_devcrit_DeepState_TestHarness_generation.cpp and cdm_rcpp_din_deterministic_devcrit_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List cdm_rcpp_din_deterministic_devcrit(Rcpp::NumericMatrix DAT, Rcpp::NumericMatrix DATRESP, Rcpp::NumericMatrix LATRESP, Rcpp::NumericVector GUESS, Rcpp::NumericVector SLIP);

TEST(CDM_deepstate_test,cdm_rcpp_din_deterministic_devcrit_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix DAT  = RcppDeepState_NumericMatrix();
  qs::c_qsave(DAT,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_din_deterministic_devcrit/inputs/DAT.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "DAT values: "<< DAT << std::endl;
  NumericMatrix DATRESP  = RcppDeepState_NumericMatrix();
  qs::c_qsave(DATRESP,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_din_deterministic_devcrit/inputs/DATRESP.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "DATRESP values: "<< DATRESP << std::endl;
  NumericMatrix LATRESP  = RcppDeepState_NumericMatrix();
  qs::c_qsave(LATRESP,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_din_deterministic_devcrit/inputs/LATRESP.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "LATRESP values: "<< LATRESP << std::endl;
  NumericVector GUESS  = RcppDeepState_NumericVector();
  qs::c_qsave(GUESS,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_din_deterministic_devcrit/inputs/GUESS.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "GUESS values: "<< GUESS << std::endl;
  NumericVector SLIP  = RcppDeepState_NumericVector();
  qs::c_qsave(SLIP,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_din_deterministic_devcrit/inputs/SLIP.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "SLIP values: "<< SLIP << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cdm_rcpp_din_deterministic_devcrit(DAT,DATRESP,LATRESP,GUESS,SLIP);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
