// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cdm_rcpp_irt_predict_DeepState_TestHarness_generation.cpp and cdm_rcpp_irt_predict_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List cdm_rcpp_irt_predict(Rcpp::NumericMatrix resp, Rcpp::NumericVector irf1, int K, int TP);

TEST(CDM_deepstate_test,cdm_rcpp_irt_predict_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix resp  = RcppDeepState_NumericMatrix();
  qs::c_qsave(resp,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_irt_predict/inputs/resp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "resp values: "<< resp << std::endl;
  NumericVector irf1  = RcppDeepState_NumericVector();
  qs::c_qsave(irf1,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_irt_predict/inputs/irf1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "irf1 values: "<< irf1 << std::endl;
  IntegerVector K(1);
  K[0]  = RcppDeepState_int();
  qs::c_qsave(K,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_irt_predict/inputs/K.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "K values: "<< K << std::endl;
  IntegerVector TP(1);
  TP[0]  = RcppDeepState_int();
  qs::c_qsave(TP,"/home/akhila/fuzzer_packages/fuzzedpackages/CDM/inst/testfiles/cdm_rcpp_irt_predict/inputs/TP.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "TP values: "<< TP << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cdm_rcpp_irt_predict(resp,irf1,K[0],TP[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
