// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// dijkstra_nodes_DeepState_TestHarness_generation.cpp and dijkstra_nodes_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector dijkstra_nodes(NumericMatrix dist, int src, NumericVector node_costs);

TEST(gretel_deepstate_test,dijkstra_nodes_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix dist  = RcppDeepState_NumericMatrix();
  qs::c_qsave(dist,"/home/akhila/fuzzer_packages/fuzzedpackages/gretel/inst/testfiles/dijkstra_nodes/inputs/dist.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dist values: "<< dist << std::endl;
  IntegerVector src(1);
  src[0]  = RcppDeepState_int();
  qs::c_qsave(src,"/home/akhila/fuzzer_packages/fuzzedpackages/gretel/inst/testfiles/dijkstra_nodes/inputs/src.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "src values: "<< src << std::endl;
  NumericVector node_costs  = RcppDeepState_NumericVector();
  qs::c_qsave(node_costs,"/home/akhila/fuzzer_packages/fuzzedpackages/gretel/inst/testfiles/dijkstra_nodes/inputs/node_costs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "node_costs values: "<< node_costs << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    dijkstra_nodes(dist,src[0],node_costs);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
