// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// weightTimesSummationCpp_DeepState_TestHarness_generation.cpp and weightTimesSummationCpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double weightTimesSummationCpp(NumericVector pastSenderTimes, double xlog, double currentTime, NumericVector weightvar);

TEST(rem_deepstate_test,weightTimesSummationCpp_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector pastSenderTimes  = RcppDeepState_NumericVector();
  qs::c_qsave(pastSenderTimes,"/home/akhila/fuzzer_packages/fuzzedpackages/rem/inst/testfiles/weightTimesSummationCpp/inputs/pastSenderTimes.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pastSenderTimes values: "<< pastSenderTimes << std::endl;
  NumericVector xlog(1);
  xlog[0]  = RcppDeepState_double();
  qs::c_qsave(xlog,"/home/akhila/fuzzer_packages/fuzzedpackages/rem/inst/testfiles/weightTimesSummationCpp/inputs/xlog.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xlog values: "<< xlog << std::endl;
  NumericVector currentTime(1);
  currentTime[0]  = RcppDeepState_double();
  qs::c_qsave(currentTime,"/home/akhila/fuzzer_packages/fuzzedpackages/rem/inst/testfiles/weightTimesSummationCpp/inputs/currentTime.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "currentTime values: "<< currentTime << std::endl;
  NumericVector weightvar  = RcppDeepState_NumericVector();
  qs::c_qsave(weightvar,"/home/akhila/fuzzer_packages/fuzzedpackages/rem/inst/testfiles/weightTimesSummationCpp/inputs/weightvar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "weightvar values: "<< weightvar << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    weightTimesSummationCpp(pastSenderTimes,xlog[0],currentTime[0],weightvar);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
