// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// manyseries_to_wordbag_DeepState_TestHarness_generation.cpp and manyseries_to_wordbag_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::DataFrame manyseries_to_wordbag(NumericMatrix data, int w_size, int paa_size, int a_size, CharacterVector nr_strategy, double n_threshold);

TEST(jmotif_deepstate_test,manyseries_to_wordbag_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix data  = RcppDeepState_NumericMatrix();
  qs::c_qsave(data,"/home/akhila/fuzzer_packages/fuzzedpackages/jmotif/inst/testfiles/manyseries_to_wordbag/inputs/data.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "data values: "<< data << std::endl;
  IntegerVector w_size(1);
  w_size[0]  = RcppDeepState_int();
  qs::c_qsave(w_size,"/home/akhila/fuzzer_packages/fuzzedpackages/jmotif/inst/testfiles/manyseries_to_wordbag/inputs/w_size.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "w_size values: "<< w_size << std::endl;
  IntegerVector paa_size(1);
  paa_size[0]  = RcppDeepState_int();
  qs::c_qsave(paa_size,"/home/akhila/fuzzer_packages/fuzzedpackages/jmotif/inst/testfiles/manyseries_to_wordbag/inputs/paa_size.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "paa_size values: "<< paa_size << std::endl;
  IntegerVector a_size(1);
  a_size[0]  = RcppDeepState_int();
  qs::c_qsave(a_size,"/home/akhila/fuzzer_packages/fuzzedpackages/jmotif/inst/testfiles/manyseries_to_wordbag/inputs/a_size.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a_size values: "<< a_size << std::endl;
  CharacterVector nr_strategy  = RcppDeepState_CharacterVector();
  qs::c_qsave(nr_strategy,"/home/akhila/fuzzer_packages/fuzzedpackages/jmotif/inst/testfiles/manyseries_to_wordbag/inputs/nr_strategy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nr_strategy values: "<< nr_strategy << std::endl;
  NumericVector n_threshold(1);
  n_threshold[0]  = RcppDeepState_double();
  qs::c_qsave(n_threshold,"/home/akhila/fuzzer_packages/fuzzedpackages/jmotif/inst/testfiles/manyseries_to_wordbag/inputs/n_threshold.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_threshold values: "<< n_threshold << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    manyseries_to_wordbag(data,w_size[0],paa_size[0],a_size[0],nr_strategy,n_threshold[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
