// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// remove_curr_col_DeepState_TestHarness_generation.cpp and remove_curr_col_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix remove_curr_col(NumericMatrix predy, int i);

TEST(bartBMA_deepstate_test,remove_curr_col_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix predy  = RcppDeepState_NumericMatrix();
  qs::c_qsave(predy,"/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/remove_curr_col/inputs/predy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "predy values: "<< predy << std::endl;
  IntegerVector i(1);
  i[0]  = RcppDeepState_int();
  qs::c_qsave(i,"/home/akhila/fuzzer_packages/fuzzedpackages/bartBMA/inst/testfiles/remove_curr_col/inputs/i.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "i values: "<< i << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    remove_curr_col(predy,i[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
