# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

moy <- function(x) {
    .Call('_vsgoftest_moy', PACKAGE = 'vsgoftest', x)
}

vestimates <- function(x, binf, bsup) {
    .Call('_vsgoftest_vestimates', PACKAGE = 'vsgoftest', x, binf, bsup)
}

