// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// collectCcat_DeepState_TestHarness_generation.cpp and collectCcat_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix collectCcat(IntegerVector xs, IntegerVector ys, int n, int m);

TEST(BiDAG_deepstate_test,collectCcat_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector xs  = RcppDeepState_IntegerVector();
  qs::c_qsave(xs,"/home/akhila/fuzzer_packages/fuzzedpackages/BiDAG/inst/testfiles/collectCcat/inputs/xs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xs values: "<< xs << std::endl;
  IntegerVector ys  = RcppDeepState_IntegerVector();
  qs::c_qsave(ys,"/home/akhila/fuzzer_packages/fuzzedpackages/BiDAG/inst/testfiles/collectCcat/inputs/ys.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ys values: "<< ys << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  qs::c_qsave(n,"/home/akhila/fuzzer_packages/fuzzedpackages/BiDAG/inst/testfiles/collectCcat/inputs/n.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  IntegerVector m(1);
  m[0]  = RcppDeepState_int();
  qs::c_qsave(m,"/home/akhila/fuzzer_packages/fuzzedpackages/BiDAG/inst/testfiles/collectCcat/inputs/m.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m values: "<< m << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    collectCcat(xs,ys,n[0],m[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
