// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// multinom_test_cpp
NumericVector multinom_test_cpp(IntegerVector x, NumericVector p, double theta);
RcppExport SEXP _ExactMultinom_multinom_test_cpp(SEXP xSEXP, SEXP pSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(multinom_test_cpp(x, p, theta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ExactMultinom_multinom_test_cpp", (DL_FUNC) &_ExactMultinom_multinom_test_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ExactMultinom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
