// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_writeBMP_DeepState_TestHarness_generation.cpp and cpp_writeBMP_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::RawVector cpp_writeBMP(const Rcpp::NumericVector image);

TEST(IFC_deepstate_test,cpp_writeBMP_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector image  = RcppDeepState_NumericVector();
  qs::c_qsave(image,"/home/akhila/fuzzer_packages/fuzzedpackages/IFC/inst/testfiles/cpp_writeBMP/inputs/image.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "image values: "<< image << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_writeBMP(image);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
