// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// surfConvHullTri_DeepState_TestHarness_generation.cpp and surfConvHullTri_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double surfConvHullTri(NumericMatrix v, NumericVector cent, NumericVector origin, double pi);

TEST(icosa_deepstate_test,surfConvHullTri_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix v  = RcppDeepState_NumericMatrix();
  qs::c_qsave(v,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/surfConvHullTri/inputs/v.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "v values: "<< v << std::endl;
  NumericVector cent  = RcppDeepState_NumericVector();
  qs::c_qsave(cent,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/surfConvHullTri/inputs/cent.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cent values: "<< cent << std::endl;
  NumericVector origin  = RcppDeepState_NumericVector();
  qs::c_qsave(origin,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/surfConvHullTri/inputs/origin.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "origin values: "<< origin << std::endl;
  NumericVector pi(1);
  pi[0]  = RcppDeepState_double();
  qs::c_qsave(pi,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/surfConvHullTri/inputs/pi.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pi values: "<< pi << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    surfConvHullTri(v,cent,origin,pi[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
