# Default Configuration, Each yaml file can have multiple configurations
default:
  # Cosmetic only options:
  base_size: 16 # Base size for Text
  expand: 0.05 # Factor to Expand horizontaly the plots with blank content
  idleness_factor: 5.5 # Resouces Idleness Text Size division Factor of base_size
  idleness_all: TRUE # Show all Resouces idleness values
  guided:
    active: TRUE
  # time: deprecated option
  title: # Overall Visualization Title
    active: TRUE # Active with directory name as Title
    #height: 0.6 # Title Size
  vanilla: # Options about X and Y axis title and values
    vertical: FALSE # If True, Remove Y axis' title and values
    horizontal: FALSE  # If True, Remove X axis' title and values
  limits: # Set the time limits used
    start: 0 # Initial Time
    #end: 10000 # Final Time

  # Visualizations in order of appearance
  atree: # plot space/time tree structure computation
    active: FALSE # Disable
    #height: # Vertical Size in the final visualization

  utiltreenode: # Plot of resource utilization by tree depth
    active: FALSE # Disable
    step: 10 # Time step used for aggregation
    #height: 2 # Vertical size for the plot

  utiltreedepth: # Plot of resource utilization by tree node
    active: FALSE # Disable
    step: 10 # Time step used for aggregation
    #height: 2 # Vertical size for the plot

  kiteration: # Visualization about application itarations
    active: TRUE # Enable
    legend: TRUE # Enable Legends
    #height: 2 # Vertical Size in the final visualization

  st: # Application State Plot over resources
    active: TRUE # Enable
    cpb: TRUE # Show Critical Path Bound makespan metric
    #height: 4 # Vertical Size in the final visualization
    idleness: TRUE # Show resource idleness %
    expand: 0.05 # Expand for y ggplot
    labels: "ALL" # Labels of the Resources names, "ALL" "1CPU_per_NODE" "1GPU_per_NODE"
    legend: TRUE # Show the plot's Legends
    makespan: TRUE # Show the application makespan
    alpha: 0.25 # Alpha value to control transparency of tasks that are not outliers
    outliers: TRUE # Differentiate outliers tasks
    abe: # Show Abe makespan metric
      active: TRUE # Enable
      label: TRUE # Enable Label
    aggregation: # If enable, aggregates the visualization tasks inside a time step.
      active: FALSE # Enable
      method: "static" # Method Used for aggregation "static" / "dynamic" (For Worker aggregation) or "nodes" for node Aggregation
      states: ["dgemm"] # Option for vinicius aggregation, Tasks for aggregation
      step: 1000 # Time step used for aggregation
    cpb_mpi: # Show Critical Path bound makespan considering MPI
      active: TRUE # Enable
      bandwidth:  1000 # TODO
      theoretical: FALSE # TODO
      tile_size: 960 # TODO
    tasks: # Shows Tasks Dependencies
      active: TRUE # Enable
      levels: 100 # Max Number of Dependencies
      list: ["1_308"] # List of Tasks Ids

  pmtool: # Create plots based on pmtool generated data
    bounds: # Shows pmtool theoretical bounds
      active: FALSE # Enable
      label: TRUE # Bound name
      alg: ["area", "cp"] # List of bounds to plot
    state: # PMtool State Chart theoretical computed by shedule
      active: FALSE # Enable
      #height: 4 # Vertical Size in the final visualization
      sched: "dmdas:" # Scheduler Used
    kiteration: # Iteration Chart
      active: FALSE
      #height: 2
      legend: TRUE
  summary_nodes:
    active: TRUE
  memory:
    combined: TRUE
    state:
      active: TRUE
      border: FALSE
      #height:
      total: TRUE
      select: "Allocating"
      #depth: deprecated
      #  active: deprecated
      #  #height: deprecated
    transfers:
      active: FALSE
      total: TRUE
      #height: 2 # Vertical Size in the final visualization
      arrow: TRUE
      border: TRUE

  starpu:
    active: TRUE
    legend: TRUE
    #height: 4

  ready:
    active: TRUE
    #height: 2
    legend: TRUE

  lackready:
    active: TRUE
    aggregation: 10
    #height: 0.3
    threshold:

  usedmemory:
    active: TRUE
    #height:
    legends:

  submitted:
    active: TRUE
    legend: TRUE
    #height: 1.5
    limit:
    step:

  mpibandwidth:
    active: TRUE
    step: 100
    legend: FALSE
    #height: 1.5
    limit:

  mpiconcurrent:
    active: TRUE
    legend: FALSE
    #height: 1.5
    step:
    limit:

  mpiconcurrentout:
    active: TRUE
    legend: FALSE
    #height: 1.5
    step:
    limit:

  mpistate:
    active: TRUE
    legend: FALSE
    #height: 1.5

  gpubandwidth:
    active: TRUE
    bound:
    #height:
    legend: FALSE
    step: 85
    total: TRUE

  activenodes: # Plot the active node count over time
    active: FALSE # Enable
    #height: 2 # Vertical size for the plot

  computingnodes: # Plot the computationally active nodes over time
    active: FALSE # Enable
    #height: 2 # Vertical size for the plot
    step: 10 # Time step used for aggregation

  gflops:
    active: FALSE
    facet: TRUE
    #height:
    legend:
    limit:
    step:
  vertical_lines:
    active: FALSE
    y_list: [1, 2]
    color_list: ["green", "gray"]
