// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// C_GP_cpp_DeepState_TestHarness_generation.cpp and C_GP_cpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix C_GP_cpp(NumericMatrix design, NumericVector response, NumericVector theta, NumericMatrix Ki, int ct);

TEST(activegp_deepstate_test,C_GP_cpp_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix design  = RcppDeepState_NumericMatrix();
  qs::c_qsave(design,"/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/inputs/design.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "design values: "<< design << std::endl;
  NumericVector response  = RcppDeepState_NumericVector();
  qs::c_qsave(response,"/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/inputs/response.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "response values: "<< response << std::endl;
  NumericVector theta  = RcppDeepState_NumericVector();
  qs::c_qsave(theta,"/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/inputs/theta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta values: "<< theta << std::endl;
  NumericMatrix Ki  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Ki,"/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/inputs/Ki.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Ki values: "<< Ki << std::endl;
  IntegerVector ct(1);
  ct[0]  = RcppDeepState_int();
  qs::c_qsave(ct,"/home/akhila/fuzzer_packages/fuzzedpackages/activegp/inst/testfiles/C_GP_cpp/inputs/ct.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ct values: "<< ct << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    C_GP_cpp(design,response,theta,Ki,ct[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
