# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fun_hcross <- function(x) {
    .Call('_ALassoSurvIC_fun_hcross', PACKAGE = 'ALassoSurvIC', x)
}

fun_subless <- function(u, lessthan) {
    .Call('_ALassoSurvIC_fun_subless', PACKAGE = 'ALassoSurvIC', u, lessthan)
}

fun_sublr <- function(u, l, r) {
    .Call('_ALassoSurvIC_fun_sublr', PACKAGE = 'ALassoSurvIC', u, l, r)
}

