// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// extractT_DeepState_TestHarness_generation.cpp and extractT_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector extractT(IntegerVector xs, IntegerVector ys, NumericMatrix ts);

TEST(BiDAG_deepstate_test,extractT_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector xs  = RcppDeepState_IntegerVector();
  qs::c_qsave(xs,"/home/akhila/fuzzer_packages/fuzzedpackages/BiDAG/inst/testfiles/extractT/inputs/xs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xs values: "<< xs << std::endl;
  IntegerVector ys  = RcppDeepState_IntegerVector();
  qs::c_qsave(ys,"/home/akhila/fuzzer_packages/fuzzedpackages/BiDAG/inst/testfiles/extractT/inputs/ys.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ys values: "<< ys << std::endl;
  NumericMatrix ts  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ts,"/home/akhila/fuzzer_packages/fuzzedpackages/BiDAG/inst/testfiles/extractT/inputs/ts.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ts values: "<< ts << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    extractT(xs,ys,ts);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
