# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Delta of the dynamic programming
#'
#' Compute the Delta of the dynamic programming in \code{\link{Rcpp}}
#'
#' @param x the matrix of rank
#' @export Compute_Cn1n2
#' @rdname Compute_Cn1n2
Compute_Cn1n2 <- function(x) {
    .Call('_MuChPoint_Compute_Cn1n2', PACKAGE = 'MuChPoint', x)
}

