# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmat <- function(id, time, result, phi1, phi0, negpred) {
    .Call('_icRSF_dmat', PACKAGE = 'icRSF', id, time, result, phi1, phi0, negpred)
}

getrids <- function(id, nsub) {
    .Call('_icRSF_getrids', PACKAGE = 'icRSF', id, nsub)
}

timeMat <- function(nsub, J, time, utime, Xmat) {
    .Call('_icRSF_timeMat', PACKAGE = 'icRSF', nsub, J, time, utime, Xmat)
}

loglikC <- function(parm, Dmat, x) {
    .Call('_icRSF_loglikC', PACKAGE = 'icRSF', parm, Dmat, x)
}

gradlikC <- function(parm, Dmat, x) {
    .Call('_icRSF_gradlikC', PACKAGE = 'icRSF', parm, Dmat, x)
}

loglikCD <- function(parm, Dmat, x) {
    .Call('_icRSF_loglikCD', PACKAGE = 'icRSF', parm, Dmat, x)
}

gradlikCD <- function(parm, Dmat, x) {
    .Call('_icRSF_gradlikCD', PACKAGE = 'icRSF', parm, Dmat, x)
}

loglikCD0 <- function(parm, Dmat) {
    .Call('_icRSF_loglikCD0', PACKAGE = 'icRSF', parm, Dmat)
}

loglikC0 <- function(parm, Dmat) {
    .Call('_icRSF_loglikC0', PACKAGE = 'icRSF', parm, Dmat)
}

gradlikCD0 <- function(parm, Dmat) {
    .Call('_icRSF_gradlikCD0', PACKAGE = 'icRSF', parm, Dmat)
}

gradlikC0 <- function(parm, Dmat) {
    .Call('_icRSF_gradlikC0', PACKAGE = 'icRSF', parm, Dmat)
}

splitpointC <- function(Dm, x, f) {
    .Call('_icRSF_splitpointC', PACKAGE = 'icRSF', Dm, x, f)
}

splitpointCD <- function(Dm, x, f) {
    .Call('_icRSF_splitpointCD', PACKAGE = 'icRSF', Dm, x, f)
}

bestsplitC <- function(Dm, Xmat, f) {
    .Call('_icRSF_bestsplitC', PACKAGE = 'icRSF', Dm, Xmat, f)
}

bestsplitCD <- function(Dm, Xmat, f) {
    .Call('_icRSF_bestsplitCD', PACKAGE = 'icRSF', Dm, Xmat, f)
}

scorefun <- function(beta, x, parm, Dmat) {
    .Call('_icRSF_scorefun', PACKAGE = 'icRSF', beta, x, parm, Dmat)
}

scorefun0 <- function(x, parm, Dmat) {
    .Call('_icRSF_scorefun0', PACKAGE = 'icRSF', x, parm, Dmat)
}

splitpt <- function(Dmat, x, parm) {
    .Call('_icRSF_splitpt', PACKAGE = 'icRSF', Dmat, x, parm)
}

bsplitC <- function(Dmat, Xmat, parm) {
    .Call('_icRSF_bsplitC', PACKAGE = 'icRSF', Dmat, Xmat, parm)
}

