# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Sum_C <- function(x) {
    .Call(`_BoostMLR_Sum_C`, x)
}

Sum_C_NA <- function(x) {
    .Call(`_BoostMLR_Sum_C_NA`, x)
}

length_C_NA <- function(x) {
    .Call(`_BoostMLR_length_C_NA`, x)
}

Mean_C <- function(x) {
    .Call(`_BoostMLR_Mean_C`, x)
}

Mean_C_NA <- function(x) {
    .Call(`_BoostMLR_Mean_C_NA`, x)
}

Which_C <- function(x, x_set) {
    .Call(`_BoostMLR_Which_C`, x, x_set)
}

Which_C_NA <- function(x, x_set) {
    .Call(`_BoostMLR_Which_C_NA`, x, x_set)
}

Which_Min_C <- function(x) {
    .Call(`_BoostMLR_Which_Min_C`, x)
}

Which_Min_C_NA <- function(x) {
    .Call(`_BoostMLR_Which_Min_C_NA`, x)
}

Which_Max_C <- function(x) {
    .Call(`_BoostMLR_Which_Max_C`, x)
}

Which_Max_C_NA <- function(x) {
    .Call(`_BoostMLR_Which_Max_C_NA`, x)
}

StdVar_C <- function(MyMat) {
    .Call(`_BoostMLR_StdVar_C`, MyMat)
}

StdVar_C_NA <- function(MyMat) {
    .Call(`_BoostMLR_StdVar_C_NA`, MyMat)
}

Match_C <- function(x_subset, x_set) {
    .Call(`_BoostMLR_Match_C`, x_subset, x_set)
}

Match_C_NA <- function(x_subset, x_set) {
    .Call(`_BoostMLR_Match_C_NA`, x_subset, x_set)
}

Approx_Match_C <- function(x, y) {
    .Call(`_BoostMLR_Approx_Match_C`, x, y)
}

Approx_Match_C_NA <- function(x, y) {
    .Call(`_BoostMLR_Approx_Match_C_NA`, x, y)
}

Diag_Matrix_C <- function(x) {
    .Call(`_BoostMLR_Diag_Matrix_C`, x)
}

Matrix_Sum_C <- function(x, y) {
    .Call(`_BoostMLR_Matrix_Sum_C`, x, y)
}

Matrix_Sum_C_NA <- function(x, y) {
    .Call(`_BoostMLR_Matrix_Sum_C_NA`, x, y)
}

l2Dist_Vector_C <- function(x1, x2, ID) {
    .Call(`_BoostMLR_l2Dist_Vector_C`, x1, x2, ID)
}

l2Dist_Vector_C_NA <- function(x1, x2, ID) {
    .Call(`_BoostMLR_l2Dist_Vector_C_NA`, x1, x2, ID)
}

randomShuffle <- function(a) {
    .Call(`_BoostMLR_randomShuffle`, a)
}

int_randomShuffle <- function(a) {
    .Call(`_BoostMLR_int_randomShuffle`, a)
}

RemoveNA <- function(x) {
    .Call(`_BoostMLR_RemoveNA`, x)
}

stl_sort <- function(x) {
    .Call(`_BoostMLR_stl_sort`, x)
}

stl_sort_NA <- function(x) {
    .Call(`_BoostMLR_stl_sort_NA`, x)
}

stl_sort_reverse <- function(x) {
    .Call(`_BoostMLR_stl_sort_reverse`, x)
}

stl_sort_reverse_NA <- function(x) {
    .Call(`_BoostMLR_stl_sort_reverse_NA`, x)
}

sort_unique_C <- function(x) {
    .Call(`_BoostMLR_sort_unique_C`, x)
}

sort_unique_C_NA <- function(x) {
    .Call(`_BoostMLR_sort_unique_C_NA`, x)
}

Which_Max_Matrix <- function(x) {
    .Call(`_BoostMLR_Which_Max_Matrix`, x)
}

Which_Max_Matrix_NA <- function(x) {
    .Call(`_BoostMLR_Which_Max_Matrix_NA`, x)
}

rowSums_C <- function(x) {
    .Call(`_BoostMLR_rowSums_C`, x)
}

rowSums_C_NA <- function(x) {
    .Call(`_BoostMLR_rowSums_C_NA`, x)
}

isNA <- function(x) {
    .Call(`_BoostMLR_isNA`, x)
}

Rho_Inv_C <- function(Rho_Value, N_Value) {
    .Call(`_BoostMLR_Rho_Inv_C`, Rho_Value, N_Value)
}

MatrixInversion_Equicorrelation_C <- function(N_Value, phi, rho) {
    .Call(`_BoostMLR_MatrixInversion_Equicorrelation_C`, N_Value, phi, rho)
}

Matrix_Vector_Multiplication_C <- function(x, y) {
    .Call(`_BoostMLR_Matrix_Vector_Multiplication_C`, x, y)
}

DataProcessing_C <- function(Org_x, Org_y, id, tm, x_miss) {
    .Call(`_BoostMLR_DataProcessing_C`, Org_x, Org_y, id, tm, x_miss)
}

BoostMLR_C <- function(Org_x, Org_y, id, tm, x, y, x_Mean, x_Std_Error, y_Mean, y_Std_Error, n, K, L, H, Dk, ni, N, unq_id, unq_tm, unq_x, id_index, Bt, Bx, Bx_Scale, Time_Add_New, Time_Unmatch, nu, M, Mod_Grad, UseRaw, Lambda_Ridge_Vec, Ridge_Penalty, Shrink, lower_perc, upper_perc, Lambda_Scale, NLambda, VarFlag, rho, phi, Verbose) {
    .Call(`_BoostMLR_BoostMLR_C`, Org_x, Org_y, id, tm, x, y, x_Mean, x_Std_Error, y_Mean, y_Std_Error, n, K, L, H, Dk, ni, N, unq_id, unq_tm, unq_x, id_index, Bt, Bx, Bx_Scale, Time_Add_New, Time_Unmatch, nu, M, Mod_Grad, UseRaw, Lambda_Ridge_Vec, Ridge_Penalty, Shrink, lower_perc, upper_perc, Lambda_Scale, NLambda, VarFlag, rho, phi, Verbose)
}

update_BoostMLR_C <- function(Org_x, Org_y, id, tm, x, y, x_Mean, x_Std_Error, y_Mean, y_Std_Error, n, K, L, H, Dk, ni, N, unq_id, unq_tm, unq_x, id_index, tm_index, x_index, Bt, Bx, Bt_H, Bx_K, Bxt, Bx_Scale, nu, M, M_New, UseRaw, Shrink, Ridge_Penalty, Lambda_Ridge_Vec, Lambda_Scale, NLambda, lower_perc, upper_perc, Lambda_List, mu, mu_List, mu_zero, Vec_zero, Error_Rate, Variable_Select, Response_Select, Beta_Hat_List, Sum_Beta_Hat_List, Beta, Beta_Hat_List_Iter, lower_Beta_Hat_Noise, upper_Beta_Hat_Noise, List_Trace_Bxt_gm, Mod_Grad, VarFlag, phi, rho, Phi, Rho, Verbose) {
    .Call(`_BoostMLR_update_BoostMLR_C`, Org_x, Org_y, id, tm, x, y, x_Mean, x_Std_Error, y_Mean, y_Std_Error, n, K, L, H, Dk, ni, N, unq_id, unq_tm, unq_x, id_index, tm_index, x_index, Bt, Bx, Bt_H, Bx_K, Bxt, Bx_Scale, nu, M, M_New, UseRaw, Shrink, Ridge_Penalty, Lambda_Ridge_Vec, Lambda_Scale, NLambda, lower_perc, upper_perc, Lambda_List, mu, mu_List, mu_zero, Vec_zero, Error_Rate, Variable_Select, Response_Select, Beta_Hat_List, Sum_Beta_Hat_List, Beta, Beta_Hat_List_Iter, lower_Beta_Hat_Noise, upper_Beta_Hat_Noise, List_Trace_Bxt_gm, Mod_Grad, VarFlag, phi, rho, Phi, Rho, Verbose)
}

predict_BoostMLR_C <- function(Org_x, tm, id, Org_y, x_Mean, x_Std_Error, y_Mean, y_Std_Error, K, L, H, Dk, unq_tm, unq_x, Bt, Bx, UseRaw, Time_Add_New, Time_Unmatch, Beta, Beta_Hat_List, testFlag, M, nu, Time_Varying, vimpFlag, vimpFlag_Coef, eps) {
    .Call(`_BoostMLR_predict_BoostMLR_C`, Org_x, tm, id, Org_y, x_Mean, x_Std_Error, y_Mean, y_Std_Error, K, L, H, Dk, unq_tm, unq_x, Bt, Bx, UseRaw, Time_Add_New, Time_Unmatch, Beta, Beta_Hat_List, testFlag, M, nu, Time_Varying, vimpFlag, vimpFlag_Coef, eps)
}

vimp_BoostMLR_C <- function(Org_x, Org_y, tm, id, x_Mean, x_Std_Error, y_Mean, y_Std_Error, n, ni, N, L, K, p, H, Dk, n_unq_tm, UseRaw, id_index, tm_index, unq_x_New, Index_Bt, vimp_set, joint, Bt, Bt_H, Bx, Bxt, Bx_K, Beta_Hat_List, Mopt, nu, rmse, Time_Varying, Vec_zero, mu_zero_vec) {
    .Call(`_BoostMLR_vimp_BoostMLR_C`, Org_x, Org_y, tm, id, x_Mean, x_Std_Error, y_Mean, y_Std_Error, n, ni, N, L, K, p, H, Dk, n_unq_tm, UseRaw, id_index, tm_index, unq_x_New, Index_Bt, vimp_set, joint, Bt, Bt_H, Bx, Bxt, Bx_K, Beta_Hat_List, Mopt, nu, rmse, Time_Varying, Vec_zero, mu_zero_vec)
}

