// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// whichMinVector__DeepState_TestHarness_generation.cpp and whichMinVector__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int whichMinVector_(NumericVector one);

TEST(icosa_deepstate_test,whichMinVector__test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector one  = RcppDeepState_NumericVector();
  qs::c_qsave(one,"/home/akhila/fuzzer_packages/fuzzedpackages/icosa/inst/testfiles/whichMinVector_/inputs/one.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "one values: "<< one << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    whichMinVector_(one);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
