# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is the main function to compute the estimator in C++
#' @keywords internal
#' @export
ivsacim_est <- function(time, event, stime, Zc, D_status, eps_2, Zc_dot) {
    .Call(`_ivsacim_ivsacim_est`, time, event, stime, Zc, D_status, eps_2, Zc_dot)
}

