// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Hvec_DeepState_TestHarness_generation.cpp and Hvec_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double Hvec(IntegerVector s, NumericVector Theta, int N);

TEST(IsingSampler_deepstate_test,Hvec_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector s  = RcppDeepState_IntegerVector();
  qs::c_qsave(s,"/home/akhila/fuzzer_packages/fuzzedpackages/IsingSampler/inst/testfiles/Hvec/inputs/s.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "s values: "<< s << std::endl;
  NumericVector Theta  = RcppDeepState_NumericVector();
  qs::c_qsave(Theta,"/home/akhila/fuzzer_packages/fuzzedpackages/IsingSampler/inst/testfiles/Hvec/inputs/Theta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Theta values: "<< Theta << std::endl;
  IntegerVector N(1);
  N[0]  = RcppDeepState_int();
  qs::c_qsave(N,"/home/akhila/fuzzer_packages/fuzzedpackages/IsingSampler/inst/testfiles/Hvec/inputs/N.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "N values: "<< N << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Hvec(s,Theta,N[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
