# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Delta3DWeightsC <- function(vx, Datasample) {
    .Call(`_GeneralizedUmatrix_Delta3DWeightsC`, vx, Datasample)
}

addRowWiseC <- function(WeightVectors, DataPoint) {
    .Call(`_GeneralizedUmatrix_addRowWiseC`, WeightVectors, DataPoint)
}

trainstepC <- function(vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid) {
    .Call(`_GeneralizedUmatrix_trainstepC`, vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid)
}

