# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

xChromosomal <- function(rmV, mfV, rk, robservedValsV, rPvalsV, rstatID, rhistobins, rhistoboundsV, rhistoData, rsafeSecs, tables) {
    .Call('_HardyWeinberg_xChromosomal', PACKAGE = 'HardyWeinberg', rmV, mfV, rk, robservedValsV, rPvalsV, rstatID, rhistobins, rhistoboundsV, rhistoData, rsafeSecs, tables)
}

SNPHWE2 <- function(obs_hets, obs_hom1, obs_hom2, midp) {
    .Call('_HardyWeinberg_SNPHWE2', PACKAGE = 'HardyWeinberg', obs_hets, obs_hom1, obs_hom2, midp)
}

SNPHWEX_tailsum <- function(high_het_side, base_probp, saved_hetsp, saved_hom1p, saved_hom2p, tie_ctp, *totalp) {
    .Call('_HardyWeinberg_SNPHWEX_tailsum', PACKAGE = 'HardyWeinberg', high_het_side, base_probp, saved_hetsp, saved_hom1p, saved_hom2p, tie_ctp, *totalp)
}

SNPHWEX <- function(female_hets, female_hom1, female_hom2, male1, male2, midp) {
    .Call('_HardyWeinberg_SNPHWEX', PACKAGE = 'HardyWeinberg', female_hets, female_hom1, female_hom2, male1, male2, midp)
}

support <- function() {
    .Call('_HardyWeinberg_support', PACKAGE = 'HardyWeinberg')
}

