// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fk_md_DeepState_TestHarness_generation.cpp and fk_md_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double fk_md(NumericVector x, NumericVector y, NumericVector x_eval, double h, NumericVector betas, double al, double C);

TEST(FKSUM_deepstate_test,fk_md_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/fk_md/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/fk_md/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector x_eval  = RcppDeepState_NumericVector();
  qs::c_qsave(x_eval,"/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/fk_md/inputs/x_eval.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x_eval values: "<< x_eval << std::endl;
  NumericVector h(1);
  h[0]  = RcppDeepState_double();
  qs::c_qsave(h,"/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/fk_md/inputs/h.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "h values: "<< h << std::endl;
  NumericVector betas  = RcppDeepState_NumericVector();
  qs::c_qsave(betas,"/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/fk_md/inputs/betas.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "betas values: "<< betas << std::endl;
  NumericVector al(1);
  al[0]  = RcppDeepState_double();
  qs::c_qsave(al,"/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/fk_md/inputs/al.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "al values: "<< al << std::endl;
  NumericVector C(1);
  C[0]  = RcppDeepState_double();
  qs::c_qsave(C,"/home/akhila/fuzzer_packages/fuzzedpackages/FKSUM/inst/testfiles/fk_md/inputs/C.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "C values: "<< C << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fk_md(x,y,x_eval,h[0],betas,al[0],C[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
